### PR TITLE
Add Cannon Duel

### PR DESCRIPTION
**Pull request by iPolish**
Add Cannon Duel

### CODE REVIEW

**Comment by Pablete1234** [comment]
@iPolish You didn't make this map, and you can't submit it. You own no copyright on that map, and you can't decide what licence goes on it.

**Comment by Matic0B** [comment]
What Pablete said

**Comment by iPolish** [comment]
Cubist letd me using he's map
W dniu czw., 2.02.2017 o 21:02 Matic0B <notifications@github.com>
napisał(a):

**Comment by Matic0B** [comment]
That doesn't mean he lets everyone to download it and for us to put a license on it

**Pull request closed without merging**
